### ISSUE TITLE
Summary table

### ISSUE THREAD

**Issue by sr320** [kubu4/paper_oly_gbs#11]
I suggest this as a summary table

![pic](http://eagle.fish.washington.edu/cnidarian/skitch/Screenshot_4_18_17__8_31_AM_1EA668E0.png)

**Comment by sr320** [comment]
[SraRunTable.txt](https://github.com/kubu4/paper_oly_gbs/files/930223/SraRunTable.txt)

**Comment by kubu4** [comment]
I'm waffling on whether or not I think this is useful for the paper or not. 

However, I think I like it as a potential addition to the project wiki...

My main reservation is that all of this info is readily available when viewing the BioProject and/or the SRA. So, it's not really a summary per se, but more of an aggregation of information.

Additionally, when looking at other Scientific Data submissions, I haven't noticed any submissions aggregating BioProject/SRA data in any fashion - just providing data citation to BioProject/SRA. However, I've only looked at three or four Scientific Data articles, so certainly have not established a full overview of the variety of ways in which authors have decided to handle NGS data.

**Comment by sr320** [comment]
Agree but is a little more meatier than current summary table and directly links data files with repo. If someone was just to look at the table- they would realize the what type of primary data is being described.

**Comment by kubu4** [comment]
Table 1 in the manuscript is solely a summary of the sequencing data, not the entire project. So, if we were to add this table, I'd view it as an additional table (i.e. Table 2).

Might as well add it and let the editor/reviewers decide, right?

**Comment by kubu4** [comment]
Removed sequencing summary table.

Added columns to aggregate table and added to OSF repo.

**Comment by kubu4** [comment]
To clarify, is the "Mbytes" column the actual FASTQ file size?

**Comment by sr320** [comment]
Not sure - just downloaded from NCBI - would be two files, and likely the compressed form?

**Comment by sr320** [comment]
https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP099079

**Comment by sr320** [comment]
I would just describe it as file size.
