### ISSUE TITLE
Add tree to repo

### ISSUE THREAD

**Issue by sr320** [kubu4/paper_oly_gbs#12]
Create directory here so we have access to everything BGI provided.
And/or does the tree live somewhere else?

**Comment by kubu4** [comment]
All BGI docs live here: [bgi_project_summary.tar.gz](http://owl.fish.washington.edu/nightingales/O_lurida/20160223_gbs/big_project_summary/)

as noted on [wiki](https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Genotype-by-sequencing-November-2015)

Although, I need to check readme file on nightingales to see if those docs are listed...

**Comment by kubu4** [comment]
I've added the BGI data summary files back to this repo: https://github.com/kubu4/paper_oly_gbs/tree/master/data

The tree is here: https://github.com/kubu4/paper_oly_gbs/blob/master/data/nj_tree.out.tre.png

That's a relatively lo-res version. The [SVG version](https://github.com/kubu4/paper_oly_gbs/blob/master/data/nj_tree.out.tre.svg) is scalable and could/should be used to generate a higher resolution image file.

I'll be updating the wiki to simplify access to these files.
