### ISSUE TITLE
Include citation for raw data.

### ISSUE THREAD

**Issue by sr320** [kubu4/paper_oly_gbs#13]
I might have missed but did not see citation of raw data.
Add this as one sentence at beginning of Data Records

**Comment by kubu4** [comment]
Right. I haven't made all the updates discussed in email chain yet. Plus, I had to figure out where in NCBI it was and make sure it could be "linked" in the same BioProject.

**Comment by sr320** [comment]
Pretty sure it is not public in SRA...
I cannot find it.

**Comment by kubu4** [comment]
Correct. It will be published today (changed it yesterday to be published today). It got lost in the shuffle, as all aspects of SRA releases have individual publication date settings (e.g. BioProject has independent publication dates, BioSamples have independent publication dates, and the SRA has independent publication dates). I didn't realize this. I figured the overarching publication date of the BioProject would apply to all items contained therein; it doesn't.

**Comment by kubu4** [comment]
Here's a roundabout way of accessing the publicly available raw data: https://www.ncbi.nlm.nih.gov/sra/?term=SRR5239009

I can't seem to find it any other way (outside of my "Submission Dashboard" thingy).
