### ISSUE TITLE
ipyrad for open source SNP calling?

### ISSUE THREAD

**Issue by ksil91** [kubu4/paper_oly_gbs#14]
I saw the comments from Scientific Data. If you were interested in using ipyrad as the "open source SNP caller", they've recently added some example notebooks for how to use the ipyrad API with Jupyter notebooks. The documentation is still kind of lacking, but if you have Jupyter/python experience I think you can follow along with their example notebooks pretty easily. I have one of my own set-up now with SSH tunneling to a HPC to function as a reproducible notebook for my pop structure stuff, so if you have issues with it I can help. Once my notebook is done I can share it with you too.

[General API info](http://ipyrad.readthedocs.io/analysis.html?highlight=tutorial%20api)
Example notebooks - [here](http://nbviewer.jupyter.org/github/dereneaton/ficus-rad/blob/master/Ficus_Jander_assembly.ipynb) and [here ](http://nbviewer.jupyter.org/github/dereneaton/pedicularis-WB-GBS/blob/master/nb1-WB-assembly.ipynb)
[plotting output docs ](https://github.com/dereneaton/ipyrad/blob/master/docs/plotting.rst) (I think the example notebook shows this easier.

**Comment by kubu4** [comment]
Thanks!

However, I'm not sure I fully understand the point/advantage of using the API over just running iPyrad. What are your thoughts on this?

**Comment by ksil91** [comment]
The nice thing about the API is you can submit a reproducible jupyter notebook along with the paper, that clearly shows the parameters used and then anyone wanting to use the data can just use the notebook as a jumping off point. But aside from that there's no other real benefit.
