### ISSUE TITLE
Data citations

### ISSUE THREAD

**Issue by sr320** [kubu4/paper_oly_gbs#6]
Re data citations - can we just provide a single DOI for the OSF repo?

There seems to be a bit of discrepancy in URLs (short versus long)
Data Citation 5: https://osf.io/cv5ty/ , Data Citation 6: https://osf.io/49a3d/ , Data Citation 7: https://osf.io/xtucy/
, Data Citation 2: http://doi.org/10.17605/OSF.IO/J8RC2).

**Comment by kubu4** [comment]
We could... Long URL is the DOI for the repo. Short URLs are links to each individual data record within the repo. I just thought it might be nicer to have direct references to each specific data record, as opposed to just referencing the entire repo over & over.

**Comment by kubu4** [comment]
But, as it turns out, I actually DO reference the entire repo over and over, even with the individual data record refs. Oh boy...

**Comment by sr320** [comment]
For ease of reading - maybe we consider a single doi - particularly if it
clear what files are what when they to go repo.

**Comment by kubu4** [comment]
Cool.
