### ISSUE TITLE
Tree, should we include?

### ISSUE THREAD

**Issue by sr320** [kubu4/paper_oly_gbs#7]
Do we have enough info on how tree was made to include it as an image in the repo?

**Comment by kubu4** [comment]
It's in the repo, but not not in the paper.

We have about as much info for it as we have for everything else. Can just
say it was made by BGI?

**Comment by kubu4** [comment]
Quick update on this. I'm struggling to find any info on how tree was constructed (thought I had seen it somewhere at some point). I'm emailing BGI for more info. Will report back when/if receive info.

**Comment by kubu4** [comment]
Not including tree. Might include later if reviewers request more.
