### ISSUE TITLE
Convert xls to csv 

### ISSUE THREAD

**Issue by sr320** [kubu4/paper_oly_gbs#9]
If nothing breaks I think csvs would be better - likely render in OSF and more "open"

**Comment by kubu4** [comment]
Might not render due to size, but I'll try it out tomorrow.

**Comment by sr320** [comment]
related - xls does not render properly once downloaded.

**Comment by kubu4** [comment]
I just downloaded all three files and all three files opened without issue.

**Comment by kubu4** [comment]
SNP.stat.csv & Data.stat.csv will render in OSF repo.

Genotype.csv will <em>not</em> render in OSF repo; it's too large.

**Comment by sr320** [comment]
let go with csv for all in OSF

**Comment by kubu4** [comment]
Updating mansucript and OSF repo with CSV info.
